# Everforest Dark Hard for Alacritty

[colors.primary]
background = "#272e33"
foreground = "#d3c6aa"

[colors.normal]
black   = "#414b50"
red     = "#e67e80"
green   = "#a7c080"
yellow  = "#dbbc7f"
blue    = "#7fbbb3"
magenta = "#d699b6"
cyan    = "#83c092"
white   = "#d3c6aa"

[colors.bright]
black   = "#475258"
red     = "#e67e80"
green   = "#a7c080"
yellow  = "#dbbc7f"
blue    = "#7fbbb3"
magenta = "#d699b6"
cyan    = "#83c092"
white   = "#d3c6aa"

[colors.cursor]
text   = "#272e33"
cursor = "#d3c6aa"

[colors.vi_mode_cursor]
text   = "CellBackground"
cursor = "CellForeground"

[colors.selection]
text       = "CellForeground"
background = "#44475a"

[colors.search.matches]
foreground = "#44475a"
background = "#50fa7b"

[colors.search.focused_match]
foreground = "#44475a"
background = "#ffb86c"

[colors.footer_bar]
background = "#272e33"
foreground = "#d3c6aa"

[colors.hints.start]
foreground = "#272e33"
background = "#dbbc7f"

[colors.hints.end]
foreground = "#dbbc7f"
background = "#272e33"
